# Generated by Django 5.1.4 on 2025-01-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
