# Generated by Django 5.1.4 on 2025-01-14 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='next_send',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 11, 3, 12, 757417)),
            preserve_default=False,
        ),
    ]
